### ISSUE TITLE
Грамматические ошибки

### ISSUE THREAD

**Issue by truenorthpaul** [Anagalanyuk/ShoppingList#10]
В программном коде (идентификаторы, комментарии, литералы и т.д.) не допускается наличие грамматических ошибок. 

Переменные, для идентификаторов которых данное правило не соблюдается:
- `clonChackeState` (метод `ShoppingList.MainForm.UpButton_Click`).

**Comment by truenorthpaul** [comment]
Переменные, для идентификаторов которых данное правило не соблюдается:
- `cloneChackeState` (метод `ShoppingList.MainForm.UpButton_Click`).

Заголовок окна.

**Comment by truenorthpaul** [comment]
Переменные, для идентификаторов которых данное правило не соблюдается:
- `cloneCheckeState` (метод `ShoppingList.MainForm.UpButton_Click`).

- `ShoppindList` (заголовок окна).

**Comment by truenorthpaul** [comment]
Ничего не изменилось.

**Comment by Anagalanyuk** [comment]
Странно вроде вчера менял.Когда включат студию проверю.У меня вчера еще интернет глючил.

**Comment by truenorthpaul** [comment]
Ничего не изменилось.
